version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-contenedor
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
