version: '1'
services:
  app:
    image: integracion-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contenedor-dsegovia
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
